# Generated by Django 2.2.3 on 2019-07-22 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postss', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ('-work_date',)},
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.BigIntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('cv', models.FileField(upload_to='')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='postss.Work')),
            ],
        ),
    ]
