# Generated by Django 2.2.3 on 2019-07-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postss', '0002_auto_20190723_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='cv',
            field=models.FileField(upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(max_length=254, verbose_name=' البريد الالكتروني'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='gender',
            field=models.CharField(max_length=50, verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=50, verbose_name='الاسم الكامل'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='number',
            field=models.BigIntegerField(verbose_name='رقم الهاتف'),
        ),
    ]
